# Generated by Django 4.1.7 on 2023-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore_api', '0007_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.ImageField(default='rating-0.png', upload_to='rating'),
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
